name: Auto-update submodule

on:
  schedule:
    - cron: "*/10 * * * *"  #- cron: "0 10 * * 1"   # every monday around 12
  workflow_dispatch:     # manual trigger button

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update submodule
        run: |
          git submodule update --remote --merge

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          if git status --porcelain | grep .; then
            git add .
            git commit -m "Auto-update submodule"
            git push
          else
            echo "No changes to commit"
          fi